### PR TITLE
full rewrite tips & tricks

### PR DESCRIPTION
**Pull request by paulcarroty**

### CODE REVIEW

**Comment by paulcarroty** [comment]
@lebensterben what happened with your IRC bridge?🌉

**Comment by lebensterben** [comment]
@paulcarroty I just quit matrix...

**Comment by paulcarroty** [comment]
And where you're communicating now?

**Comment by lebensterben** [comment]
I'm excommunicated.

**Comment by paulcarroty** [comment]
What kind of religious sect you're in? Dis-communication is their first rule ☺️

Good luck, anyway.

**Pull request merged**
